[project]
name = "recipe-agentic-rag-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "streamlit>=1.40.1",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
]
